In [24]:
from ucimlrepo import fetch_ucirepo 
import pandas as pd
import numpy as np
import math
import pickle

In [25]:

  
# fetch dataset 
ai4i_2020_predictive_maintenance_dataset = fetch_ucirepo(id=601) 
# data (as pandas dataframes) 
x = ai4i_2020_predictive_maintenance_dataset.data.features 
y = ai4i_2020_predictive_maintenance_dataset.data.targets 
df = pd.concat([x,y], axis =1)

display(df.head(25))
df = df.drop(columns= ["TWF","HDF","PWF","OSF","RNF"])
display(df.head(25))

display(df.info())

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Machine failure,TWF,HDF,PWF,OSF,RNF
0,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0
5,M,298.1,308.6,1425,41.9,11,0,0,0,0,0,0
6,L,298.1,308.6,1558,42.4,14,0,0,0,0,0,0
7,L,298.1,308.6,1527,40.2,16,0,0,0,0,0,0
8,M,298.3,308.7,1667,28.6,18,0,0,0,0,0,0
9,M,298.5,309.0,1741,28.0,21,0,0,0,0,0,0
10,H,298.4,308.9,1782,23.9,24,0,0,0,0,0,0
11,H,298.6,309.1,1423,44.3,29,0,0,0,0,0,0
12,M,298.6,309.1,1339,51.1,34,0,0,0,0,0,0
13,M,298.6,309.2,1742,30.0,37,0,0,0,0,0,0
14,L,298.6,309.2,2035,19.6,40,0,0,0,0,0,0
15,L,298.6,309.2,1542,48.4,42,0,0,0,0,0,0
16,M,298.6,309.2,1311,46.6,44,0,0,0,0,0,0
17,M,298.7,309.2,1410,45.6,47,0,0,0,0,0,0
18,H,298.8,309.2,1306,54.5,50,0,0,0,0,0,0
19,M,298.9,309.3,1632,32.5,55,0,0,0,0,0,0
20,H,298.9,309.3,1375,42.7,58,0,0,0,0,0,0
21,L,298.8,309.3,1450,44.8,63,0,0,0,0,0,0
22,M,298.9,309.3,1581,30.7,65,0,0,0,0,0,0
23,L,299.0,309.4,1758,25.7,68,0,0,0,0,0,0
24,M,299.0,309.4,1561,37.3,70,0,0,0,0,0,0

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Machine failure
0,M,298.1,308.6,1551,42.8,0,0
1,L,298.2,308.7,1408,46.3,3,0
2,L,298.1,308.5,1498,49.4,5,0
3,L,298.2,308.6,1433,39.5,7,0
4,L,298.2,308.7,1408,40.0,9,0
5,M,298.1,308.6,1425,41.9,11,0
6,L,298.1,308.6,1558,42.4,14,0
7,L,298.1,308.6,1527,40.2,16,0
8,M,298.3,308.7,1667,28.6,18,0
9,M,298.5,309.0,1741,28.0,21,0
10,H,298.4,308.9,1782,23.9,24,0
11,H,298.6,309.1,1423,44.3,29,0
12,M,298.6,309.1,1339,51.1,34,0
13,M,298.6,309.2,1742,30.0,37,0
14,L,298.6,309.2,2035,19.6,40,0
15,L,298.6,309.2,1542,48.4,42,0
16,M,298.6,309.2,1311,46.6,44,0
17,M,298.7,309.2,1410,45.6,47,0
18,H,298.8,309.2,1306,54.5,50,0
19,M,298.9,309.3,1632,32.5,55,0
20,H,298.9,309.3,1375,42.7,58,0
21,L,298.8,309.3,1450,44.8,63,0
22,M,298.9,309.3,1581,30.7,65,0
23,L,299.0,309.4,1758,25.7,68,0
24,M,299.0,309.4,1561,37.3,70,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Type                 10000 non-null  object
 1   Air temperature      10000 non-null  float64
 2   Process temperature  10000 non-null  float64
 3   Rotational speed     10000 non-null  int64
 4   Torque               10000 non-null  float64
 5   Tool wear            10000 non-null  int64
 6   Machine failure      10000 non-null  int64
dtypes: float64(3), int64(3), object(1)
memory usage: 547.0+ KB

None

In [26]:
#Power in watts
df["Power"]  = (df["Torque"] * df["Rotational speed"] * (math.pi /30)).round(0)
df["Overstrain"] = (df["Torque"] * df["Tool wear"]).round(0)
df["Temperature difference"] = (df["Process temperature"] - df["Air temperature"]).round(0)
display(df.sample(30))

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Machine failure,Power,Overstrain,Temperature difference
9928,M,298.4,308.5,1576,27.4,55,0,4522.0,1507.0,10.0
1324,M,298.8,310.1,1243,74.5,194,1,9697.0,14453.0,11.0
8508,M,298.4,309.7,1679,33.3,167,0,5855.0,5561.0,11.0
641,L,297.9,309.5,1390,47.9,127,0,6972.0,6083.0,12.0
1926,L,298.0,307.7,1606,30.8,17,0,5180.0,524.0,10.0
1628,L,297.9,307.8,1451,38.2,80,0,5804.0,3056.0,10.0
8700,M,297.3,308.7,1451,43.8,24,0,6655.0,1051.0,11.0
6988,L,300.7,311.1,1478,46.8,165,0,7244.0,7722.0,10.0
6913,L,300.8,311.2,1481,38.5,181,0,5971.0,6968.0,10.0
7599,L,300.5,311.0,1759,28.3,13,0,5213.0,368.0,10.0
315,L,297.9,308.4,1646,40.6,175,0,6998.0,7105.0,10.0
5581,M,302.5,312.1,1454,47.6,37,0,7248.0,1761.0,10.0
2675,L,299.7,309.3,1574,35.8,6,0,5901.0,215.0,10.0
1986,L,298.1,307.6,1498,42.9,171,0,6730.0,7336.0,10.0
5239,L,303.7,313.0,1753,29.0,42,0,5324.0,1218.0,9.0
7072,M,300.7,310.6,1439,41.7,184,0,6284.0,7673.0,10.0
9451,H,298.0,308.7,1536,39.6,99,0,6370.0,3920.0,11.0
640,M,297.9,309.6,1515,38.8,124,0,6156.0,4811.0,12.0
9508,L,299.2,310.4,1611,36.4,32,0,6141.0,1165.0,11.0
2495,M,299.1,308.8,1491,41.0,209,0,6402.0,8569.0,10.0
9774,H,298.6,309.5,1375,41.0,39,0,5904.0,1599.0,11.0
6748,H,301.7,311.0,2016,19.3,180,0,4075.0,3474.0,9.0
4106,L,301.9,310.5,1425,51.1,173,0,7625.0,8840.0,9.0
1915,L,298.0,307.7,1492,38.7,202,0,6047.0,7817.0,10.0
7612,M,300.5,311.4,1743,27.6,46,0,5038.0,1270.0,11.0
4938,M,303.5,312.4,1606,30.1,98,0,5062.0,2950.0,9.0
2773,L,299.9,309.4,1858,22.5,22,0,4378.0,495.0,10.0
1623,L,297.7,307.6,1921,22.9,68,0,4607.0,1557.0,10.0
9632,M,299.0,310.0,1337,57.4,146,0,8037.0,8380.0,11.0
3340,M,301.5,310.8,1452,44.1,157,0,6706.0,6924.0,9.0

In [27]:
#Normalising the type , will jsut detect it the overstrain exceeds 11,000
df["Type"] = df["Type"].replace({
    "L": 0,
    "M": 1,
    "H": 2
})
df  = df.astype({"Type":"int"})
display(df.head(15))

C:\Users\tbarn\AppData\Local\Temp\ipykernel_17700\1405694736.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Type"] = df["Type"].replace({

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Machine failure,Power,Overstrain,Temperature difference
0,1,298.1,308.6,1551,42.8,0,0,6952.0,0.0,10.0
1,0,298.2,308.7,1408,46.3,3,0,6827.0,139.0,10.0
2,0,298.1,308.5,1498,49.4,5,0,7749.0,247.0,10.0
3,0,298.2,308.6,1433,39.5,7,0,5928.0,276.0,10.0
4,0,298.2,308.7,1408,40.0,9,0,5898.0,360.0,10.0
5,1,298.1,308.6,1425,41.9,11,0,6253.0,461.0,10.0
6,0,298.1,308.6,1558,42.4,14,0,6918.0,594.0,10.0
7,0,298.1,308.6,1527,40.2,16,0,6428.0,643.0,10.0
8,1,298.3,308.7,1667,28.6,18,0,4993.0,515.0,10.0
9,1,298.5,309.0,1741,28.0,21,0,5105.0,588.0,10.0
10,2,298.4,308.9,1782,23.9,24,0,4460.0,574.0,10.0
11,2,298.6,309.1,1423,44.3,29,0,6601.0,1285.0,10.0
12,1,298.6,309.1,1339,51.1,34,0,7165.0,1737.0,10.0
13,1,298.6,309.2,1742,30.0,37,0,5473.0,1110.0,11.0
14,0,298.6,309.2,2035,19.6,40,0,4177.0,784.0,11.0

In [28]:

df = df.rename(columns= lambda x: x.lower().replace(" ","_"))
display(df.head())

,type,air_temperature,process_temperature,rotational_speed,torque,tool_wear,machine_failure,power,overstrain,temperature_difference
0,1,298.1,308.6,1551,42.8,0,0,6952.0,0.0,10.0
1,0,298.2,308.7,1408,46.3,3,0,6827.0,139.0,10.0
2,0,298.1,308.5,1498,49.4,5,0,7749.0,247.0,10.0
3,0,298.2,308.6,1433,39.5,7,0,5928.0,276.0,10.0
4,0,298.2,308.7,1408,40.0,9,0,5898.0,360.0,10.0

Power feature: Mechanical power produced by the motor. Too low or too high could indicate a fault indicated previsouly by PWF
Overstrain feature: Cummulativemechanical stress overtime, previously indicated by OSF
Temp difference: How effectively heat generated by the process is dissipating

In [29]:
print(df.info())
print(df.head())

df.to_pickle("../data/clean.pkl")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   type                    10000 non-null  int64
 1   air_temperature         10000 non-null  float64
 2   process_temperature     10000 non-null  float64
 3   rotational_speed        10000 non-null  int64
 4   torque                  10000 non-null  float64
 5   tool_wear               10000 non-null  int64
 6   machine_failure         10000 non-null  int64
 7   power                   10000 non-null  float64
 8   overstrain              10000 non-null  float64
 9   temperature_difference  10000 non-null  float64
dtypes: float64(6), int64(4)
memory usage: 781.4 KB
None
   type  air_temperature  process_temperature  rotational_speed  torque  \
0     1            298.1                308.6              1551    42.8
1     0            298.2                308.7              1408    46.3
2     0            298.1                308.5              1498    49.4
3     0            298.2                308.6              1433    39.5
4     0            298.2                308.7              1408    40.0

   tool_wear  machine_failure   power  overstrain  temperature_difference
0          0                0  6952.0         0.0                    10.0
1          3                0  6827.0       139.0                    10.0
2          5                0  7749.0       247.0                    10.0
3          7                0  5928.0       276.0                    10.0
4          9                0  5898.0       360.0                    10.0