In [10]:
from ucimlrepo import fetch_ucirepo 
import pandas as pd
import numpy as np
import math

In [6]:

  
# fetch dataset 
ai4i_2020_predictive_maintenance_dataset = fetch_ucirepo(id=601) 
# data (as pandas dataframes) 
x = ai4i_2020_predictive_maintenance_dataset.data.features 
y = ai4i_2020_predictive_maintenance_dataset.data.targets 
df = pd.concat([x,y], axis =1)

display(df.head(25))
df = df.drop(columns= ["TWF","HDF","PWF","OSF","RNF"])
display(df.head(25))

display(df.info())

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Machine failure,TWF,HDF,PWF,OSF,RNF
0,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0
5,M,298.1,308.6,1425,41.9,11,0,0,0,0,0,0
6,L,298.1,308.6,1558,42.4,14,0,0,0,0,0,0
7,L,298.1,308.6,1527,40.2,16,0,0,0,0,0,0
8,M,298.3,308.7,1667,28.6,18,0,0,0,0,0,0
9,M,298.5,309.0,1741,28.0,21,0,0,0,0,0,0
10,H,298.4,308.9,1782,23.9,24,0,0,0,0,0,0
11,H,298.6,309.1,1423,44.3,29,0,0,0,0,0,0
12,M,298.6,309.1,1339,51.1,34,0,0,0,0,0,0
13,M,298.6,309.2,1742,30.0,37,0,0,0,0,0,0
14,L,298.6,309.2,2035,19.6,40,0,0,0,0,0,0
15,L,298.6,309.2,1542,48.4,42,0,0,0,0,0,0
16,M,298.6,309.2,1311,46.6,44,0,0,0,0,0,0
17,M,298.7,309.2,1410,45.6,47,0,0,0,0,0,0
18,H,298.8,309.2,1306,54.5,50,0,0,0,0,0,0
19,M,298.9,309.3,1632,32.5,55,0,0,0,0,0,0
20,H,298.9,309.3,1375,42.7,58,0,0,0,0,0,0
21,L,298.8,309.3,1450,44.8,63,0,0,0,0,0,0
22,M,298.9,309.3,1581,30.7,65,0,0,0,0,0,0
23,L,299.0,309.4,1758,25.7,68,0,0,0,0,0,0
24,M,299.0,309.4,1561,37.3,70,0,0,0,0,0,0

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Machine failure
0,M,298.1,308.6,1551,42.8,0,0
1,L,298.2,308.7,1408,46.3,3,0
2,L,298.1,308.5,1498,49.4,5,0
3,L,298.2,308.6,1433,39.5,7,0
4,L,298.2,308.7,1408,40.0,9,0
5,M,298.1,308.6,1425,41.9,11,0
6,L,298.1,308.6,1558,42.4,14,0
7,L,298.1,308.6,1527,40.2,16,0
8,M,298.3,308.7,1667,28.6,18,0
9,M,298.5,309.0,1741,28.0,21,0
10,H,298.4,308.9,1782,23.9,24,0
11,H,298.6,309.1,1423,44.3,29,0
12,M,298.6,309.1,1339,51.1,34,0
13,M,298.6,309.2,1742,30.0,37,0
14,L,298.6,309.2,2035,19.6,40,0
15,L,298.6,309.2,1542,48.4,42,0
16,M,298.6,309.2,1311,46.6,44,0
17,M,298.7,309.2,1410,45.6,47,0
18,H,298.8,309.2,1306,54.5,50,0
19,M,298.9,309.3,1632,32.5,55,0
20,H,298.9,309.3,1375,42.7,58,0
21,L,298.8,309.3,1450,44.8,63,0
22,M,298.9,309.3,1581,30.7,65,0
23,L,299.0,309.4,1758,25.7,68,0
24,M,299.0,309.4,1561,37.3,70,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Type                 10000 non-null  object
 1   Air temperature      10000 non-null  float64
 2   Process temperature  10000 non-null  float64
 3   Rotational speed     10000 non-null  int64
 4   Torque               10000 non-null  float64
 5   Tool wear            10000 non-null  int64
 6   Machine failure      10000 non-null  int64
dtypes: float64(3), int64(3), object(1)
memory usage: 547.0+ KB

None

In [26]:
#Power in watts
df["Power"]  = (df["Torque"] * df["Rotational speed"] * (math.pi /30)).round(0)
df["Overstrain"] = (df["Torque"] * df["Tool wear"]).round(0)
df["Temperature difference"] = (df["Process temperature"] * df["Air temperature"]).round(0)
display(df.sample(30))

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Machine failure,Power,Overstrain,Temperature difference
8246,L,299.0,310.3,1552,39.9,114,0,6485.0,4549.0,92780.0
7298,L,300.1,310.5,1532,36.0,109,0,5776.0,3924.0,93181.0
3836,L,302.4,311.2,1466,43.9,152,0,6739.0,6673.0,94107.0
8018,L,301.0,311.9,1889,23.5,198,0,4649.0,4653.0,93882.0
2913,L,300.7,309.6,1541,34.6,131,0,5584.0,4533.0,93097.0
704,L,297.7,308.9,1516,33.7,92,0,5350.0,3100.0,91960.0
8924,H,297.1,308.2,1527,42.2,199,0,6748.0,8398.0,91566.0
9492,L,299.1,309.9,1586,36.6,215,0,6079.0,7869.0,92691.0
9511,L,299.1,310.3,1449,40.7,40,0,6176.0,1628.0,92811.0
3811,M,302.1,310.7,1608,30.3,81,0,5102.0,2454.0,93862.0
8320,M,298.8,309.7,1453,47.7,101,0,7258.0,4818.0,92538.0
7188,L,300.4,310.4,1286,56.8,46,0,7649.0,2613.0,93244.0
6792,L,301.2,310.6,1811,24.0,84,0,4552.0,2016.0,93553.0
2717,M,299.5,309.1,1422,45.3,103,0,6746.0,4666.0,92575.0
929,L,295.6,306.0,1419,51.1,7,0,7593.0,358.0,90454.0
2167,H,299.6,309.1,1588,41.3,0,0,6868.0,0.0,92606.0
4198,M,302.4,311.1,1432,44.5,195,0,6673.0,8678.0,94077.0
1778,L,298.6,308.2,1325,54.0,41,0,7493.0,2214.0,92029.0
1620,L,297.9,307.7,1492,43.7,59,0,6828.0,2578.0,91664.0
3202,L,300.2,309.2,1430,43.4,24,0,6499.0,1042.0,92822.0
6575,M,301.4,310.5,1451,45.3,183,0,6883.0,8290.0,93585.0
1359,L,298.7,310.2,1404,50.3,54,0,7395.0,2716.0,92657.0
4935,L,303.4,312.3,1479,42.8,92,0,6629.0,3938.0,94752.0
9696,L,298.9,309.9,1404,39.8,62,0,5852.0,2468.0,92629.0
1852,M,297.6,307.1,1526,39.1,39,0,6248.0,1525.0,91393.0
774,L,296.8,307.9,1448,48.8,31,0,7400.0,1513.0,91385.0
6800,M,301.1,310.6,1310,48.8,103,0,6695.0,5026.0,93522.0
5885,L,301.3,311.1,1647,28.2,140,0,4864.0,3948.0,93734.0
7500,L,300.2,311.8,1410,51.4,189,0,7589.0,9715.0,93602.0
3418,H,301.6,310.6,1555,40.4,139,0,6579.0,5616.0,93677.0

In [31]:
#Normalising the type , will jsut detect it the overstrain exceeds 11,000
df.loc[df["Type"] == "M", "Overstrain"] -= 1000
df.loc[df["Type"] == "H", "Overstrain"] -= 2000
display(df.head(15))

,Type,Air temperature,Process temperature,Rotational speed,Torque,Tool wear,Machine failure,Power,Overstrain,Temperature difference
0,M,298.1,308.6,1551,42.8,0,0,6952.0,3000.0,91994.0
1,L,298.2,308.7,1408,46.3,3,0,6827.0,139.0,92054.0
2,L,298.1,308.5,1498,49.4,5,0,7749.0,247.0,91964.0
3,L,298.2,308.6,1433,39.5,7,0,5928.0,276.0,92025.0
4,L,298.2,308.7,1408,40.0,9,0,5898.0,360.0,92054.0
5,M,298.1,308.6,1425,41.9,11,0,6253.0,3461.0,91994.0
6,L,298.1,308.6,1558,42.4,14,0,6918.0,594.0,91994.0
7,L,298.1,308.6,1527,40.2,16,0,6428.0,643.0,91994.0
8,M,298.3,308.7,1667,28.6,18,0,4993.0,3515.0,92085.0
9,M,298.5,309.0,1741,28.0,21,0,5105.0,3588.0,92236.0
10,H,298.4,308.9,1782,23.9,24,0,4460.0,6574.0,92176.0
11,H,298.6,309.1,1423,44.3,29,0,6601.0,7285.0,92297.0
12,M,298.6,309.1,1339,51.1,34,0,7165.0,4737.0,92297.0
13,M,298.6,309.2,1742,30.0,37,0,5473.0,4110.0,92327.0
14,L,298.6,309.2,2035,19.6,40,0,4177.0,784.0,92327.0

Power feature: Mechanical power produced by the motor. Too low or too high could indicate a fault indicated previsouly by PWF
Overstrain feature: Cummulativemechanical stress overtime, previously indicated by OSF
Temp difference: How effectively heat generated by the process is dissipating